### ISSUE TITLE
How can I access the training data that has been used?

### ISSUE THREAD

**Issue by joaquinCaceres** [selimfirat/pysad#6]
Hello everyone, 

When a model has been trained, such as LocalOutlierProbability. How can I access the training data that has been used?

I have managed to access the first dataset that is used when initialising the model: LocalOutlierProbability.model.data, but I need the new batch train data which is generated after call fit_partial(X).

Thanks in advance!

**Comment by selimfirat** [comment]
Hi,

Sorry for a very late response. You can store the X used to call fit_partial. Handling of data is done at the user side.

Please feel free to reopen the issue.
