### ISSUE TITLE
There is a problem in the method fit_partial in reference_window_model.py

### ISSUE THREAD

**Issue by eljabrichaymae** [selimfirat/pysad#7]
In case initial_window_X is not provided, the training of the model will stop when the size cur_window_X is equal to window_size - 1 and restart when the size cur_window_X can be divided by sliding_size. This problem occurs mainly when window_size and sliding_size have different parity.

**Comment by selimfirat** [comment]
Sorry for a very late answer. I am not sure I correctly understood the issue.

Unfortunately, I couldn't reproduce the case when "the training of the model will stop when the size cur_window_X is equal to window_size - 1".

"restart when the size cur_window_X can be divided by sliding_size. This problem occurs mainly when window_size and sliding_size have different parity" This is correct behavior as far as I understood. As per the documentation (https://pysad.readthedocs.io/en/latest/generated/pysad.models.integrations.ReferenceWindowModel.html):

"For every sliding_size instnaces, it resets the model by training new model_cls instance with the reference window."

Please feel free to reopen the issue. I appreciate if you can give an example.
